/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlayerRouteImport } from './routes/player'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoomTestRouteImport } from './routes/room.test'
import { Route as RoomIdRouteImport } from './routes/room.$id'

const PlayerRoute = PlayerRouteImport.update({
  id: '/player',
  path: '/player',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomTestRoute = RoomTestRouteImport.update({
  id: '/room/test',
  path: '/room/test',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomIdRoute = RoomIdRouteImport.update({
  id: '/room/$id',
  path: '/room/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/player': typeof PlayerRoute
  '/room/$id': typeof RoomIdRoute
  '/room/test': typeof RoomTestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/player': typeof PlayerRoute
  '/room/$id': typeof RoomIdRoute
  '/room/test': typeof RoomTestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/player': typeof PlayerRoute
  '/room/$id': typeof RoomIdRoute
  '/room/test': typeof RoomTestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/player' | '/room/$id' | '/room/test'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/player' | '/room/$id' | '/room/test'
  id: '__root__' | '/' | '/player' | '/room/$id' | '/room/test'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlayerRoute: typeof PlayerRoute
  RoomIdRoute: typeof RoomIdRoute
  RoomTestRoute: typeof RoomTestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/player': {
      id: '/player'
      path: '/player'
      fullPath: '/player'
      preLoaderRoute: typeof PlayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/test': {
      id: '/room/test'
      path: '/room/test'
      fullPath: '/room/test'
      preLoaderRoute: typeof RoomTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$id': {
      id: '/room/$id'
      path: '/room/$id'
      fullPath: '/room/$id'
      preLoaderRoute: typeof RoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlayerRoute: PlayerRoute,
  RoomIdRoute: RoomIdRoute,
  RoomTestRoute: RoomTestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
